Feat/error boundary
vierim/YaPomogayu-frontend pull request #117
Opened 2023-08-23 06:55 UTC by Gyxer513

Обработчик готов, для проверки обернул им компонент map.

2023-08-24 09:37 UTC, anastasia-bazaeva requested changes
Хорошая работа, при корректном вызове с пропсами ошибка отображается на экране, новые изображения с дополнительных экранов добавлены. 
Но есть несколько замечаний к коду, они связаны в основном с тем, что обработчик сейчас не совсем обрабатывает внутри себя ошибку, он ожидает на вход готовое условие от компонента. Если сэмулировать какую-то ошибку, например, отключив сервер, обработчик не ловит ее и не срабатывает, т.к. ждет на вход что компонент уже сам все обработал и передал готовый тип ошибки.
У нас есть булево значение isFailed в сторе, посмотри, пожалуйста, понадобится ли что-то еще, чтобы понимать, что случилась ошибка и обработать, какая именно.
Заметила еще что на макете на экране блокировки не хватает загнутой стрелочки, сможешь добавить?

2023-08-24 09:37 UTC, anastasia-bazaeva commented on src/features/error-boundary/index.tsx
> +  errorType?: 'connect' | 'bloked' | 'any';
Давай попробуем определить тип ошибки не на входе в обработчик, а внутри обработчика. Мы можем один раз описать логику, как мы определяем тип ошибки (прямо здесь, или вынести это определение в отдельную функцию в utils и вызвать ее здесь), и тогда остальные компоненты, использующие ErrorBoundary не будут вынуждены использовать логику определения типов ошибок внутри себя каждый раз, когда используется ErrorBoundary.

2023-08-24 09:37 UTC, anastasia-bazaeva commented on src/pages/profile-map/index.tsx
> +          errorType="bloked"
предлагаю убрать хардкод и пока написать для теста обработчика некое событие или переключатель, вызывающий нужные ошибки, чтобы потом другие ребята могли тестировать работу компонента волонтера, не испытывая трудностей.

2023-08-29 06:40 UTC, Gyxer513 commented
Привет! Сделал несколько кнопок c ошибками. 
![image](https://github.com/vierim/YaPomogayu-frontend/assets/102280477/ed19e560-e227-47aa-b843-396e57c33f94)
 
Логику проверки типа ошибки реализовывать не стал, так как у нас только две фиксированные ошибки с отдельным поведением, остальные выкидываются в виде уведомления.

2023-09-01 17:40 UTC, anastasia-bazaeva approved these changes
Отличная работа! 
Осталось поправить одну деталь, и можно будет отдавать Владимиру на оценку.

2023-09-01 17:40 UTC, anastasia-bazaeva commented on src/pages/profile-map/index.tsx
> +  const { error } = useAppSelector((state) => state.user);
Лучше доставать ошибку напрямую из state.user.error

2023-09-01 20:25 UTC, Gyxer513 commented
Привет! Исправил.

2023-09-02 08:55 UTC, vierim requested changes
Общая концепция работы централизованного обработчика ошибок сделана не совсем корректно. Нужно внести некоторые правки:
1) Централизованный обработчик ошибок может быть только один. Он на то и централизованный. Поэтому в обработчик нужно обернуть все приложение в компоненте App.
2) Ошибка - это отдельная сущность нашего приложения. Она как бы стоит рядом с другими сущностями - пользователями, задачами и тд. Поэтому не логично хранить ее в сторе пользователя. Давай сделаем отдельный стор для ошибки, где мы сможем создать такие поля, которые нам нужны.
3) Далее в компоненте, где мы встречаем ошибку API (например, isError из RTK Query, мы меняем стейт нашей центральной ошибки и она отображется).
4) Исходя из правок выше надо посмотреть, что верстка ошибок корректная. Сейчас она не соответствует макету немного - https://github.com/vierim/YaPomogayu-frontend/issues/87
5) Так как обработчик у нас централизованный, нам надо где-то централизованно хранить факт ошибки. И это либо контекст, либо Редакс. Но не все вместе.
6) Мне кажется, что с типом ошибки надо работать как-то изящнее, а не просто строковыми литералами.

2023-09-02 08:55 UTC, vierim commented on src/pages/profile-map/index.tsx
Сейчас файл получился битый. Возьми, пожалуйста, из develop рабочий вариант.

2023-09-07 19:14 UTC, vierim approved these changes

2023-09-07 19:15 UTC, merged