Features/create request
vierim/YaPomogayu-frontend pull request #45
Opened 2023-07-13 10:51 UTC by AleksandrDronov

2023-07-14 07:31 UTC, vierim requested changes
Комментарии поо коду добавил. Отдельно добавлю, что нужно проработать формат времени - сейчас он не российский, и обязательное заполнение полей - адрес, время, выбор типа задачи.

2023-07-14 07:31 UTC, vierim commented on src/features/create-request/ui/steps/date-step/date-step.tsx
>  import { formatDate } from "../../../libs/format-date";
Желательно отказаться от сложного формата даты вручную и использовать date-fns

2023-07-14 07:31 UTC, vierim commented on src/features/create-request/ui/steps/request.stories.tsx
> +            apikey: "0cdc3c9a-36a5-482d-8090-9c74d8d5f92e",
API ключ лучше брать из файла с константами.

2023-07-14 07:31 UTC, vierim commented on src/shared/ui/map/index.tsx
> +    }}
Я немного запутался. В данном файле мы оборачиваем все с компонент YMaps. Вопрос - с какой целью мы оборачиваем в такой же компонент все приложение в файле /src/app/index.tsx?

2023-07-14 07:31 UTC, vierim commented on src/pages/recipient/index.tsx
> +                  handleClickAddTaskButton={() => dispatch(openPopup())}
Не уверен, что есть смысл делать безымянную фукнцию в данном случае. Может лучше сразу вызывать dispatch?

2023-07-14 07:31 UTC, vierim commented on src/shared/ui/input-address/index.tsx
> +  inputAttributes?: React.InputHTMLAttributes<HTMLInputElement>;
Давай выненесем это из объявления интерфейса и расширим этими аттрибута интерфейс, как это сделано в обычном инпуте - https://disk.yandex.ru/i/lyF8VbnwhgXKfg

2023-07-14 12:25 UTC, AleksandrDronov commented on src/features/create-request/model/create-request.ts
> +  coordinates: undefined,
Оставил так. С пустым массивом больше кода.

2023-07-16 11:30 UTC, AleksandrDronov commented on src/shared/ui/overlaying-popup/index.tsx
>          />
не понял, почем не нужен.

2023-07-16 11:35 UTC, AleksandrDronov commented on src/shared/ui/overlaying-popup/index.tsx
>          {children}
Всё хватает вроде. Смысл в том, что внутри дива один див и children. Внутренниму диву не нужен закрывающий тег, так как внутри него ничего нет. Об это и говорит IDE. Ты навреное подумал что во внутреннем диве должен быть children, но нет. Они на одном. уровне

2023-07-16 11:41 UTC, AleksandrDronov commented on src/features/create-request/ui/steps/common-step/common-step.tsx
Пока нет возможности. Держит дизайн. Выяснилось, что при создании заявки нет поля для title. Дизайнер решает нужно ли оно.

2023-07-16 12:02 UTC, AleksandrDronov commented on src/shared/ui/map/index.tsx
> +    }}
Мучился с этими провайдерами. Пробовал различно обоваричвать. Отдельно карту, отдельно всё приложение. В итоге падало с ошибкой. Только данный вариант рабочий. Вначале у меня была обернута только карта. Но при такой обертке если прыгать между шагами формы туда-сюда, то  не видимо не успевает прогрузиться апи яндекс карт и падает приложение.

2023-07-16 12:06 UTC, AleksandrDronov commented on src/pages/recipient/index.tsx
> +                  handleClickAddTaskButton={() => dispatch(openPopup())}
Тогда нужно типизировать handleClickAddTaskButton чисто под dispatch и получится что только можно передать функцию dispatch. Пропадает универсальность пропса.

2023-07-16 12:13 UTC, AleksandrDronov commented on src/shared/ui/input-address/index.tsx
> +  inputAttributes?: React.InputHTMLAttributes<HTMLInputElement>;
Ошибка типов [https://ibb.co/18FRfvX](https://ibb.co/18FRfvX)

2023-07-16 12:22 UTC, vierim commented on src/shared/ui/overlaying-popup/index.tsx
>          {children}
Тег div - это парный тег и конструкция <div /> не валидная.

2023-07-16 12:54 UTC, AleksandrDronov commented on src/shared/ui/overlaying-popup/index.tsx
>          {children}
В IDE попробуй. [https://ibb.co/vw55wDL](https://ibb.co/vw55wDL)

2023-07-16 15:21 UTC, merged