userdata slightly touched
vierim/YaPomogayu-frontend pull request #61
Opened 2023-07-28 14:52 UTC by anastasia-bazaeva

Текущая модель данных пользователя в сторе сама по себе отвечает поставленным задачам, а вот содержание вложенной в нее UserInfo я бы рассмотрела подробнее. Права и роли зависят от содержимого UserInfo, поэтому предлагаю сосредоточиться на этой сущности и внести в нее ряд изменений. 
![дата ранее и сейчас](https://github.com/vierim/YaPomogayu-frontend/assets/102751317/e4f8f05b-352c-4e85-b4a3-bec80f2ef554)

**1. Предлагаю убрать два разных поля checked и approved, и добавить единую систему статусов** для аккаунтов всех ролей. Это позволит не хранить нужные данные в нескольких полях, и сразу покажет проверенный это аккаунт, или нет, и какие ему возможности стоит предоставить, исходя из комбинации роли и статуса. Также в будущем этапов прохождения верификации админами и, соответственно, статусов может стать больше, и чтобы не создавать третье, четвертое и т.д. поле, я бы просто дополнила список возможных статусов новым значением. Ниже предлагаю схему, где описано, какие сейчас статусы могут быть у каких ролей, а также предлагаю таблицу с описанием, какие условия для той или иной роли должны выполняться для получения конкретного статуса. 

![требования к статусам](https://github.com/vierim/YaPomogayu-frontend/assets/102751317/382d083c-a2d5-4c8a-ac13-9bff08afb5a4)
![статусы](https://github.com/vierim/YaPomogayu-frontend/assets/102751317/0ccbef72-d82f-4761-aa67-d6fe6ef723c2)

**2. Для прав администраторов я бы добавила поле permissions, которое представляет из себя массив** с доступными правами. В текущем проекте в правах админов хранилось одно число, но бриф дает понять, что комбинация этих прав может быть любой, состоять из разного набора прав, и они не зависят друг от друга, могут быть хоть все сразу, поэтому я предлагаю хранить эти права в виде массивов с id и названием права. На беке это должна быть отдельная таблица прав для каждого пользователя, но на фронте нам нужно получить эти данные массивом. В случае, когда прав станет больше, этот массив может просто дополниться новыми значениями. 
Я немного порисерчила на тему прав в плане дальнейшей реализации, и нашла [статью](https://habr.com/ru/articles/428143/), [репозиторий](https://github.com/nurzhan-saktaganov/react-rbac-guard) оттуда и [песочницу](https://codesandbox.io/s/znmxlw59jm?file=/src/components/examples/PermissionBased/Demo.jsx), где используется ролевая модель для разграничения доступов. Можно будет использовать подобный подход для реализации разграничения возможностей простых администраторов. Волонтерам достаточно проверки доступов в прямом соответствии статусам, т.к. для них менее гибкая система прав.

**3. В модель пользователя стоит добавить количество завершенных заявок**, т.к. их количество - это одно из условий для перехода Волонтера на новый статус. Сейчас используется поле score, которое показывает количество баллов (сейчас 1 задание = 1 балл), но поскольку заказчик может изменить систему вознаграждения баллами за задания, а у некоторых администраторов есть права на увеличение количества баллов Волонтера, предлагаю использовать именно данные о завершенных заявках. Причем не о просто закрытых заявках, а именно об успешно завершенных.

**4.  Ключи предлагаю хранить в виде количества,** а не булева значения. Заказчик указывает их именно в количественном обозначении, и при развитии проекта вероятна возможность получения Волонтером более 1 ключа. Для нас изменение не столь значительно, но в будущем если ключей может быть более 1, проект легко сможет подстроиться под эти обновления. 

**5. В данном пул-реквесте я поправила типы, код некоторых компонентов и истории для сторибука, но я не трогала swagger.**

2023-07-28 16:33 UTC, KirillKamratov commented
LGTM!
В целом, очень грамотно все сделано, лично у меня замечаний нет

2023-07-29 11:47 UTC, vierim requested changes
Ты проделала огромную работу! 
Я попрошу тебя после внесения правок сделать файл README.md в папке /src/entities/user/model, чтобы сохранить подробное описание модели с картинками. Очень доходчиво получилось.

Небольшие замечания по ролевой модели:
1. Мне кажется, что не совсем корректно описана модель для "Мастер Админ". У данной роли в рамках нашего приложения нет статуса. Он не может быть создан, неактивирован, активирован или деактивирован. Он может быть только один, имеет доступ ко всему и предоставлен нам мирозданием (ручным созданием в базе данных). И в рамках нашего интерфейса мы не можем предусмотреть какие либо действия с ним.
2. В рамках решения задачи авторизации пользователя и разграничения прав доступа нам разве может понадобится статус "deactivated" в сторе? Мне кажется, что если пользователь деактивирован, то он не сможет залогиниться и получить JWT-ключ еще на уровне бека. Как ты считаешь?
3. По пункту 2 я с тобой согласен. Мы можем для компонентов, у которых нам надо проверять права доступа хранить в каком-то виде данные, с какими разрешениями как этот компонент работает и дальше, получая резрешения текущего пользователя через хук сравнивать (в идеале нужен хук типа useRoleMatch, который будет получать permissions компонента, лезть в хранилище и сравнивать с данными польхователя; на выходе булевое значение, как вариант) и либо рендерить, либо отдавать null, либо что-то промежуточное (например, disabled).
4. По пункту 3 я скорее не согласен. Если нам где-то в макете нужно отобразить количество выполненных заданий - хорошо, давай добавим. А вот статус волонтера лучше получать с бека. По-моему рассчитывать такие условия на фронте не совсем корректно.
5. По ключам нет возражений.
6. Сваггер мы больше не трогаем - теперь это на стороне бека. Я думаю, что пока нет бека, мы можем подключить json-server и быстренько в него накидывать нужные нам модели и ответы сервера.

2023-07-29 13:48 UTC, anastasia-bazaeva commented
@vierim Спасибо за ревью! Изучила комментарии, могу дополнить, почему предлагаю именно то, что предлагаю:
1. Мастер Админ такой же юзер, как и все. Он может иметь любые статусы, хоть только активный статус с самого его создания, мы можем это не проверять, но он такой же юзер, как и остальные, просто с другой ролью, и тут дело скорее в единообразии данных. Даже если он создан вручную, у него же должен быть какой-то статус, показывающий его активность. Кроме того, я закладываю возможности дропунуть текущего мастер админа и сделать его деактивированным, в случае утечки его данных для входа в аккаунт, поэтому считаю, что в таком случае, статусная модель отловит это и отработает корректно и предсказуемо. 
2. Да, конечно, деактивированный пользователь - тоже пользователь, его запись не удаляется из базы данных, а статус может быть восстановлен админом согласно брифу. Если он деактивирован, он должен получить от бека ключ и залогиниться, чтобы увидеть какое-нибудь сообщение о том, что он деактивирован. Если на основании деактивации не давать ему залогиниться, то он просто не поймет, что случилось и будет пытаться стучаться в учетку и начнет репортить, что сайт сломался. Еще можно деактивированному показывать не только сообщение о том, что его аккаунт деактивирован, но и давать посетить страницу с правилами и положениями ресурса, которые он мог нарушить и/или страницу контактов, чтобы он мог обратиться в поддержку и узнать о причинах блокировки и возможностях ее снятия. 
3. Принято.
4. Да, согласна, я тут зачем-то заложила заранее, чтобы можно было отображать завершенные заявки + делать доп.проверку, но проверки - это уже задача бека, а нам пока завершенные заявки не нужны. Уберу, оставлю баллы, спасибо, что отловил ошибку!
5. Принято.
6. Хорошо, что свагер не понадобится. Я пыталась потыкаться, но не разобралась)

2023-07-29 14:43 UTC, vierim commented
1. Я согласен, что для построение ролевой модели доступов нам нужно единообразие в данных. 
Я призываю еще раз обдумать тот факт, что для нас - мастер админ просто есть, он один и дан нам свыше и со всеми правами. Человек заходит с логином и паролем и получает соответствующие права мастер-админа от бека. Ну и мы у себя в сторе или хуке каким-то образом помечаем, что ему можно все.
В случае компрометации данных логин мастер-админа должен быть деактивирован на стороне сервера и создан новый тамже вручную. У нас нет возможности наделять кого-то правами супер-пользователя через интерфейс, как и блочить супер-пользователя. 
По сути в данном пункте я прошу тебя исправить диаграмму, из которой следует, что у мастер-админа есть какой-то путь до активирован/деактивирован. В рамках нашего стора он просто есть, активирован и далее без вариантов.
У меня такое ощущение, что в данном пункте ты снова углубилась в продумывание модели на стороне бека, тебе так не кажется?
2. Утверди, пожалуйста, этот момент с Ольгой. В брифе ничего такого нет. Сама по себе идея хорошая, но ее надо подробно проработать, особенно на стороне заказчика.
6. Ты сможешь взять на себя задачу подключить к проекту [json-server](https://www.npmjs.com/package/json-server) в рамках отдельной таски?

2023-07-29 15:15 UTC, anastasia-bazaeva commented
@vierim Спасибо за уточнения!
1. Да, схемы поменяла. Сори, я сначала не так поняла и решила, что мы мастера хотим отдельно чуточку по-другому хранить. А так да, я понимаю, что мы мастера не проверяем сейчас никак, кроме как по роли.

![статусы](https://github.com/vierim/YaPomogayu-frontend/assets/102751317/331c3a18-2ce7-4496-ba34-ad6ed7088797)
![требования к статусам](https://github.com/vierim/YaPomogayu-frontend/assets/102751317/4f2bf6a2-ffd6-4cb0-aac8-1d17cab2b295)

2. Согласуем с ней этот момент. 
3. Да, давай я попробую погрузиться и сделать.

2023-07-30 15:33 UTC, anastasia-bazaeva commented
@vierim обсудили с Олей, что показывать деактивированному, его мы вообще не пускаем и показываем попап. Поэтому удалила статус для деактивированного из возможных вариантов хранения в сторе. Что показываем, пока не знаем, ждем попап в макете

2023-07-30 15:37 UTC, vierim approved these changes

2023-07-30 15:38 UTC, merged