Feat: added dropdown component
vierim/YaPomogayu-frontend pull request #63
Opened 2023-07-29 19:01 UTC by KirillKamratov

Создал компонент dropdown, добавил немного стилизации, которой не было в макете (к примеру, наведении на список - курсор становится в состояние pointer, также, появляется затемнение при наведении на выбираемый элемент из выпадающего списка), но мне показалось, что так будет более user friendly.

2023-07-30 16:00 UTC, vierim requested changes
Есть несколько концептуальных моментов, которые нужно поправить:
1) Сейчас непонятно, как передать в компонент информацию, если какой-то из пунктов отмечен (например, пришел нам с бека).
2) Полное не соответствие макету - https://disk.yandex.ru/i/SPCNB1g0CEEPAw
Посмотреть все данные по дизайну данного элемента можно в [фигме](https://www.figma.com/file/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=609%3A4585&mode=dev) на странице UI-kit.

2023-08-02 06:09 UTC, anastasiian3 commented
Привет! Очень круто получилось, молодец!
У меня совсем немного вопросов: 
1. Не понимаю функцию пропса selected, за что он отвечает? Использовала компонент таким образом, как ты его забил в сторибук, все работает, и там selected не присутствует. 
![image](https://github.com/vierim/YaPomogayu-frontend/assets/102759284/979e0691-e20b-4777-86b3-a39474030055)
Может быть, как-то не так логику понимаю?
2. По поводу самого сторибука: предлагаю вытащить компонент из папки, папка, думаю, излишняя
![image](https://github.com/vierim/YaPomogayu-frontend/assets/102759284/600470e7-7a7f-4368-a084-36c43440b418)
3. Вот, что случается, когда забиваешь слишком много вариантов для выбора
![image](https://github.com/vierim/YaPomogayu-frontend/assets/102759284/c58ab2bc-8304-448d-91fb-775edd78dec8)
Может, ограничить высоту, прокрутка добавится? 

Ну и просто вкусовщина: я бы оставила галочку так, как в макете, мне кажется, очень много обводок. Но это опять же на любителя, может, Владимиру тоже нравится такой вариант исполнения.

2023-08-02 07:45 UTC, KirillKamratov commented
Привет! 
Спасибо за ревью!

Касательно комментов 1 и 2 - согласен, их исправил.

Касательно коммента 3 - в к макете компонент ограничен высотой в 532px, у меня 2 элемента - кнопка и сам список. Список ограничен в 484px (Общая высота в 532px - высота кнопки), согласно макета. Поэтому - тут не согласен, но если нужно ограничить еще - пусть Владимир скажет, я ограничу

Касательно обводки на галке- на макете действительно, галка без обводки, но при скачивании svg с макета копируется почему-то с галочкой, Владимиру также писал об этом.

2023-08-02 18:50 UTC, vierim requested changes
Классная работа. Уже очень похоже на настоящий Select, только со стилями из макета.

Я указал на пару технических правок в коде. Их нужно исправить. Также нужно внести несколько стилевых деталей в твой компонент:
1) В соответствии с UI-kit https://disk.yandex.ru/i/K8pcPsyNZs2Thw нужно
- добавить опциональную возможность передавать в компонент label;
- плейсхолдер по цвету отличается от выбранного элемента;
- на свернутом Select должна быть галочка, показывающая, что его можно развернуть.
2) От себя добавлю следующие пункты:
- при развернутом Select вот тут https://disk.yandex.ru/i/dExbtIV5R9vXkA должно быть пусто, иначе пользователь видит две галочки и ему хочется сойти с ума;
- у меня ощущение, что мы не учли какие-то еще базовые моменты при создании компонента, поэтому я тебя попрошу в /src/features/create-request/ui/steps/task-step/task-step.tsx заменить используемый компонент Select на твой Dropdown и убедиться, что все корректно работает.

2023-08-02 18:50 UTC, vierim commented on src/shared/ui/dropdown/index.tsx
> +  onChange: (item: Option) => void;
Я предполагаю, что данная функция предусмотрена для проброса выбранного значения наверх, туда где мы рендерим данный Select. Но я не вижу, где она используется в компоненте.

2023-08-02 18:50 UTC, vierim commented on src/shared/ui/dropdown/styles.module.css
> +  margin: 0 auto;
Внешнее позиционирование не стоит задавать внутри компонента. Лучше это позиционирование передавать из вне. Тоже самое могу сказать про ширину. Посмотри, как в данном проекте многие компонены используют логику передачи внешних стилей через пропс extClassName. Это отлично решает задачу кастомизации позиционирования и размера элемента в зависимости от того места, где его используют.

2023-08-02 18:50 UTC, vierim commented on src/shared/ui/dropdown/styles.module.css
> +  font-family: 'Golos', sans-serif;
В том же файле common.css указаны типовые шрифты для проекта. Их можно подключать через className - посмотри, как это сделано в других компонентах.

2023-08-02 18:53 UTC, vierim commented
Забыл добавить относительно высоты компонента. Может в макете высота и 532px, но ни при каких расладах он не должен быть больше высоты экрана или уезжать за пределы экрана без возможности просмотра элементов. Вот в этом месте надо очень хорошо подумать, как такое поведение реализовать.

2023-08-02 19:37 UTC, KirillKamratov commented on src/shared/ui/dropdown/styles.module.css
> +  border: solid 1px #818C99;
Исправил

2023-08-04 09:14 UTC, KirillKamratov commented
@vierim Привет!

Встроил в task-step, как ты и говорил, но пришлось в девтулзах отключить грид, потому что сейчас сетка немного ломается, из-за того что попытался вставить в рандомном месте, на странице контактов

<img width="1440" alt="Снимок экрана 2023-08-04 в 12 12 44" src="https://github.com/vierim/YaPomogayu-frontend/assets/102192184/39518433-24df-4118-b5d2-e66f1d5195ea">

На скрине 1 видно, что DropDown закрыт, под ним есть окошко для описания задачи.

<img width="1440" alt="Снимок экрана 2023-08-04 в 12 13 23" src="https://github.com/vierim/YaPomogayu-frontend/assets/102192184/2a261dc8-1f00-409b-a1b4-8933615ad920">

На скрине 2 видно, что DropDown открыт, и ничего не съехало и не поломалось

2023-08-05 18:37 UTC, KirillKamratov commented
Добавил мобильное разрешение

2023-08-07 16:26 UTC, anastasiian3 approved these changes
Мне прям очень нравится, как все выглядит, элемент получился очень классным!

2023-08-08 08:50 UTC, vierim approved these changes
Отличная работа!

2023-08-08 08:50 UTC, merged