feat: added login page
vierim/YaPomogayu-frontend pull request #64
Opened 2023-07-30 12:52 UTC by anastasiian3

1. Собрала страницу входа.
2. Добавила новый компонент PasswordInput, необходимые иконки, закинула все в Storybook.
3. Отступила от макета и добавила иконку глазка для отображения пароля администратора при необходимости.

2023-08-01 16:34 UTC, anastasia-bazaeva requested changes
Молодец, проделана хорошая работа, но есть недочеты. 
1. На мобильном разрешении есть несоответствие макету. Нужно будет пройтись по всем элементам и проверить их размеры и центрирование, а также все нужно будет уместить, чтобы ничего не вываливалось из окошка (на цвет кнопки vk в твоем варианте не обращай внимание, на ней сейчас hover, с ним все ок).
Мобильная версия в текущей версии:
![логин03](https://github.com/vierim/YaPomogayu-frontend/assets/102751317/6509cec1-011b-4c06-b3d8-31ffdb2057bf)
Согласно макету:
![Уже есть аккаунт](https://github.com/vierim/YaPomogayu-frontend/assets/102751317/b297729a-a299-4505-ab41-fb9925225544)
2. Обратила внимание, что цвет фона приложения отличается от макета, сможешь заодно подправить, где нужно?
3. Остальные комментарии в коде.

2023-08-01 16:34 UTC, anastasia-bazaeva commented on src/shared/ui/password-input/password-input.stories.ts
> +export const Default: Story = {
Давай как в истории с обычным инпутом добавим вариант для отображения инпута пароля с ошибкой

2023-08-03 06:12 UTC, vierim commented
Мне пока больше добавить нечего. Нужно исправить моменты, указанные Анастасией. Только загрухи сначала актуальный develop - там шапка в мобильной поровнее уже)

2023-08-05 10:05 UTC, anastasiian3 commented on src/pages/login/index.tsx
> +              <Input
Сделала, в данный момент инпут с паролем выдает ошибку, если пользователь набирает пароль, который меньше 6 символов.

2023-08-05 10:05 UTC, anastasiian3 commented on src/pages/login/index.tsx
> +                required
Выполнено

2023-08-05 10:05 UTC, anastasiian3 commented on src/shared/ui/password-input/password-input.stories.ts
> +export const Default: Story = {
Добавила Interactions + немного доп. описаний в сторибук

2023-08-05 12:03 UTC, anastasiian3 commented
Загрузила девелоп, исправила мобильное отображение, залила необходимое в сторибук. Из-за того, что инпут проходит валидацию, корректно ошибка отображается только на странице error, где срабатывают Interactions

2023-08-05 18:56 UTC, anastasiian3 commented
Добавила отображение дефолтного элемента в сторибук, отредактировала пропсы, были ненужные.

2023-08-06 10:15 UTC, anastasia-bazaeva reviewed
Молодец, что разобралась со сторибуком и добавлением текста ошибки. Но логика все еще работает не совсем корректно:
1. Проверка длины введенного пароля происходит только при клике снаружи инпута. Так, если введен слишком короткий пароль, подсказка выскочит только при нажатии на глазик или в любое другое место.
![логин08](https://github.com/vierim/YaPomogayu-frontend/assets/102751317/ceb7f5bf-0636-4ef1-9e57-37440bc37f3e)

![логин04](https://github.com/vierim/YaPomogayu-frontend/assets/102751317/5decf8b1-848a-442b-bc45-d7cc52c28452)

![логин07](https://github.com/vierim/YaPomogayu-frontend/assets/102751317/13b06381-50a0-41a8-9dd3-096bcf9b35e3)

2. Если ввести длинный пароль, после чего нажать на глазик, а потом стереть часть пароля и нажать на сабмит, форма отправляется:
![логин02](https://github.com/vierim/YaPomogayu-frontend/assets/102751317/37a438ae-5ddf-40f4-a090-7c9d7d6725b4)

3. Если после этого дописать пароль длиннее, чтобы он удовлетворял правилу, форма не отправится повторно:

![логин03](https://github.com/vierim/YaPomogayu-frontend/assets/102751317/a2eb8cd9-a94e-4677-828f-43dbf6c3b186)

4. На мобильном разрешении все еще выпадают инпуты:
![логин06](https://github.com/vierim/YaPomogayu-frontend/assets/102751317/953b8747-b0e0-4396-a2b1-6f72dc1661df)

5. Фон страницы логин не белый, а светло-голубой. В макете цвет #FBFDFF

2023-08-07 14:57 UTC, anastasia-bazaeva commented
@vierim про то, чтобы опустить условие для валидации согласна, что давайте упростим - достаточно подсветить сообщение, что поле должно быть заполнено. По поводу своих комментариев - я думаю, что бест практис на сегодняшний день все же подсвечивать подсказки в момент ввода, и мне показалось, что это будет проще и возможно убрало бы ошибку, когда валидация по сабмиту несвоевременно отрабатывает и не пропускает на бек валидный вариант, пропуская не валидный при определенных условиях.
Но ты прав, что можно валидацию в принципе поставить отдельной задачей, а данный ПР рассматривать без нее.

Про мобильную версию не согласна. Проект живой и пойдет нам в портфолио, потенциальный работодатель обязательно откроет сайт проекта на мобильном устройстве, и тут нам нужно показать, что мы умеем делать резиновую верстку. Я сделала пример отображения на не самом маленьком экране и не самом старом телефоне iPhone 12 pro. Я например, пользуюсь SE 2, который новее чем 12pro, и у меня значительно меньше экран, там вообще может часть функционала отпасть.

2023-08-07 18:09 UTC, anastasiian3 commented
**По итогу:** логику проверки пароля оставила прежней. С валидацией логина ничего не делала. Логику отображения ошибок/отправки формы обработала. Мобилку поправила, теперь все "резиновое". Соответственно, работала над комментариями 2-5 + пометками в коде.

2023-08-07 19:08 UTC, anastasia-bazaeva reviewed
Отличная работа! У нас теперь потрясающий гибкий мобильный интерфейс для страницы входа, все отображается корректно на всех доступных для тестирования устройствах.
Фон приложения соответствует макету, причем ты сделала не только для своей страницы, а поменяла фон сразу для всего приложения, это отличный подход к решению таких проблем 👍
Остался один момент с ошибкой при вводе.

2023-08-07 20:21 UTC, anastasiian3 commented on src/shared/ui/password-input/index.tsx
> +            : 'Вы ввели неправильный пароль'
Оставила условную валидацию, которая просто иллюстрирует, что пароль короткий, если пользователь внес только 1 символ. Думаю, когда у данной страницы будет валидация, такие ошибки будут появляться без проблем

2023-08-07 20:31 UTC, anastasia-bazaeva approved these changes
Хорошо, что поменяли текст ошибки и условие

2023-08-09 13:02 UTC, vierim approved these changes
Отличная работа!

2023-08-09 13:02 UTC, merged