Feat/edit viewer info
vierim/YaPomogayu-frontend pull request #67
Opened 2023-07-30 18:41 UTC by VladislavSerKir

- Компонент модального окна отображается как надо. Как для обычного разрешения, так для мобильных устройств
- Модальное окно как показывается, так и закрывается на соответствующие кнопки и на esc. Единственное по оверлею не закрывается
- Данные загружаются в компонент модалки из стора (user), обновление данных нужно тестировать в связке с сервером
- Не до конца понял и реализовал загрузку фотографии на сервер, в будущем нужно дальше дорабатывать, когда и сервер и ручки появятся. Для загрузки фото наверно лучше еще одну кнопку сделать, так как приходится 2 запроса делать. Один на отправку объекта данных пользователя, второй на отправку файла с бинарным типом.
- Созданный компонент крестика закрытия добавлены в storybook и корректно отображаются

2023-07-31 13:49 UTC, anastasia-bazaeva requested changes
Хорошая работа! 
По верстке все согласно макету. Единственное, я бы на всякий случай уточнила у Оли, точно ли не нужен крестик для попапа в мобильной версии, т.к. у всех попапов, кроме этого, в макете на мобилке эти крестики есть. 
Комментарии по коду оставила, там есть небольшие замечания.

2023-07-31 13:49 UTC, anastasia-bazaeva commented on src/shared/api/model/index.ts
> +      body: body,
Чтобы отправить файл, нужно будет добавить блок headers.
headers: {
        'content-type': body.type,
        'content-length': `${body.size}`, // <-- обязательно строкой
      },

2023-07-31 13:49 UTC, anastasia-bazaeva commented on src/shared/ui/light-popup/index.tsx
> +              avatarLink={avatarLink}
Можно добавить условие, если у нас есть подгруженный файл, то отобразить вместо аватара либо выбранный файл, либо уведомление в кружке, что выбранное изображение загружено. Без этого пока визуально не понятно, что пользователь что-то смог выбрать и готов отправить изменения на сервер.

2023-07-31 13:49 UTC, anastasia-bazaeva commented on src/shared/ui/light-popup/index.tsx
> +      // uploadAvatar(viewerData.id, formData);
Не очень корректно, что компонент напрямую обращается к серверу. Функция uploadAvatar работает аналогично функции updateUser. Я бы использовала их единообразно - в блоке extraReducers в src/entities/user/model/user.ts, аналогично меняя стор и подгружая в него ответ с сервера с новым аватаром.. Там же можно будет обработать кейсы со статусами запроса - pending, fullfilled, rejected

2023-07-31 16:18 UTC, vierim commented on src/shared/ui/light-popup/index.tsx
> +              avatarLink={avatarLink}
Согласен с данным комментарием. При подгрузке новой аватарки надо сразу ее отображать на месте старой.

2023-07-31 16:23 UTC, vierim commented on src/shared/ui/light-popup/index.tsx
> +      // uploadAvatar(viewerData.id, formData);
Давай немного подумаем, как должен работать компонент. Предположим, что пользователь:
- нажал на ссылку "Изменить фото", 
- загрузил новый файл, 
- картинка подгрузилась в интерфейса на аватар, 
- человек, предположим понял, что некрасивая аватарка и не нажал на кнопку "Сохранить" в нашем компоненте. 

- Разве в этом случае аватарка должна измениться на сервере?

2023-07-31 16:45 UTC, vierim requested changes
Мне кажется, что в какой-то момент произошло взаимное непонимание в рамках данного треда - https://app.pachca.com/chats/6430843?message=67587541

Давай еще раз проговорим. 

У нас был (и должен остаться) компонент - EditViewerInfo. Именно он отвечает за логику изменения данных пользователя. 
Ты столкнулся с проблемой, что текущий компонент MainPopup, который отвечает за логику попапа, отличается от того дизайна, который нужен по макету (а именно - другой крестик и возможно еще какие-то небольшие отличия).
И я тебе написал, что сделай новый компонент LightPopup, который будет отображаться так, как тебе нужно. Но речь шла именно про компонент обертку, у которого будет только задачи попапа (показываться поверх элементов, открываться, закрываться). То есть мы инкапсулируем логику попапа в один компонент, внутри которого уже будем рендерить десятки других разных компонентов.

И уже в LightPopup нужно обертывать EditViewerInfo.

А у тебя в коде вся логика работы с данными пользователя ушла в LightPopup. Нужно это поправить.

2023-07-31 16:45 UTC, vierim commented on src/entities/user/ui/user-info/index.tsx
> +import { UpdateUserInfo } from 'entities/user/types';
Тут можно указать не просто import, а `import type { UpdateUserInfo } from ...`

2023-07-31 17:11 UTC, anastasia-bazaeva commented on src/shared/api/model/index.ts
> +      body: body,
@vierim По идее пишут, что если использовали FormData для загрузки файла, то тип файла должен определиться автоматически при отправке. Но когда я тестировала ветку, у меня тип файла определяется только при мануальном указании headers. 
Вот так если отправляем без headers:
![файл00](https://github.com/vierim/YaPomogayu-frontend/assets/102751317/835eef70-db96-4fcd-a48b-02d19e68b713)

А вот так с headers:
![файл01](https://github.com/vierim/YaPomogayu-frontend/assets/102751317/3363941b-2683-4c7c-9fa7-6ede58d2d2a0)

Я может не вижу просто с фронта этих данных, и они зашиты уже в то, что уходит в первом случае, но исходила из того, что хорошо бы на бек тип явно отправлять в заголовке, чтобы если там не картинка, или картинка в неподдерживаемом формате, бек смог заранее отловить этот момент и ответить ошибкой.

2023-07-31 20:03 UTC, VladislavSerKir commented
Учел все предложения. Единственное по прежнему смущает приходится делать 2 запроса. Удалил handlerAvatar так как нет кнопки сохранения именно его. Нашел один из способов решения загрузки с помощью 1 запроса на [stackoverflow](https://ru.stackoverflow.com/questions/1036244/%D0%9A%D0%B0%D0%BA-%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%D0%B0%D1%82%D1%8C-%D0%BF%D0%BE-http-%D0%BE%D0%B4%D0%BD%D0%B8%D0%BC-post-%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%BE%D0%BC-%D1%84%D0%B0%D0%B9%D0%BB-%D0%B4%D0%B2%D0%BE%D0%B8%D1%87%D0%BD%D1%8B%D0%B5-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5-%D0%B8-json) но полагаю что обработка данных на бэке будет сложнее.

2023-08-01 17:05 UTC, anastasia-bazaeva reviewed
1. Круто! Аватарка теперь меняется, если подтянуть новую картинку 🔥 . 
2. Можно лучше - Заметила, что мы отправляем все данные пользователя (текстовые + картинка) по сабмиту даже тогда, когда ничего в них не изменили или если поменяли только аватар/только текст.
3. Ключик пропал из ЛК волонтера - там была единичка напротив иконки, теперь не отображается.
4. Можно лучше - можно будет сделать закрытие попапа по клику на оверлей.

2023-08-01 20:12 UTC, VladislavSerKir commented
Ключик пропал из за того что в **позапрошлых** pull requst удалили хард код, но модель юзера не поменяли. Поэтому приходит объект  с полем `keys: true`.
![2023-08-01_23-01-48](https://github.com/vierim/YaPomogayu-frontend/assets/83783362/9f4744d0-d2d4-45c9-b95b-7f8f41f54ddd)
Завтра могу начать делать закрытие по оверлею, хотя изначально у меня в задаче этого не было, но понимаю что нужно на будущее

2023-08-02 05:40 UTC, vierim commented
@anastasia-bazaeva Вопрос с заголовками, который подняла в первом ревью, очень хороший. Но лично мне не понятный. Давай не будем решать его в рамках данного PR. Я могу тебе поставить тебе задачу - обсудить этот момент с нашим тех-лидом? Просто меня смущает попытка определить тип файла на фронте и как-то на это ориентироваться, ведь никто не мешает подменить заголовки при отправке.

@VladislavSerKir Хочу подсветить несколько моментов:
1) Не вижу никакой проблемы отправлять несколько запросов не сервер. По крайне мере пока у нас нет точных ручек с бека. Ты асинхронно отправляешь какие-то данные, ну и пусть летят. Сервер он ведь и стоит для того, чтобы принимать запросы и отвечать на них. И если речь не идет о DDOS милионами запросов, то проблем нет.

2) Оверлей мы сейчас не троагем. Как я говорил - это отдельная большая таска в рамках работы со слоями попапов.

3) Компонент LightPopup сделан некорректно. Скажи, как мне использовать его, например, для отображения вот такого попапа - https://disk.yandex.ru/i/J1jFYhBpUEuVqg (если есть непонимание, чего вообще от тебя хотят, возможно есть смысл обсудить это на 1-1).

2023-08-02 18:56 UTC, VladislavSerKir commented
Исправил организацию компонентов в т.ч. LightPopup. Остальная функциональность модального окна не нарушена. 
@vierim  раз уж я разбирался с темой модалок попробовал реализовать overlay click но в отдельной ветке [feat/modal-overlay-test](https://github.com/vierim/YaPomogayu-frontend/tree/feat/modal-overlay-test), которую отдельно запушил. Работает как надо, но тестировал только с одним модальным окном. Если не нужна будет удали

2023-08-03 06:22 UTC, vierim requested changes
1) [feat/modal-overlay-test](https://github.com/vierim/YaPomogayu-frontend/tree/feat/modal-overlay-test) - если все работает, так добавляй в эту ветку. Отлично же, что разобрался. На счет не 1 попапа, а нескольких - будут проблемы, будет чинить.

2) Нашел небольшую багу в твоем компоненте. Суть в следующем - нужно сбрасывать загруженный файл аватарки при закрытии модального окна без сохранения.
Как увидеть багу:
- нажимаем на кнопку настроек, появляется твоя модалка, 
- загружаем новую фотграфию, 
- закрываем модалку без сохранения изменений, 
- снова нажимаем на кнопку настроек. 
По идеи, раз мы не сохранили изменения, аватарка должна быть старой, а сейчас там уже новая аватарка.

2023-08-05 11:09 UTC, VladislavSerKir commented
Удалось пофиксить баги и ошибки из прошлых сообщений. 
1) На данный момент работают оба запроса на отправку изменений фотографии и формы.
2) Модалка нормально открывается/закрывается, единственное **но** по организации кода: пришлось перенести навешивание обработчиков на функцию `handleEscKeydown` в компонент формы, чтобы можно было обнулять данные при закрытии. 
  В принципе когда будет redux и отрисовка на фронтенде измененных данных формы, можно будет ее вернуть на компонент выше там где и была. А в сам компонент добавить утилитарную функцию, которая будет брать данные из сущности user redux и проверять по наличию изменений значений по ключам пользователя.

2023-08-06 10:39 UTC, anastasia-bazaeva reviewed
Отличная работа! От меня остались только пара комментариев в самых сложных местах:
1. Подгруженная аватарка корректно сбрасывается, если мы передумали вносить изменения до сабмита 👍 Но она сейчас не сбрасывается после отправки формы, и при повторном открытии попапа подменяет текущий аватар на загруженный ранее файл. На живом проекте при успешном обновлении формы пользователь ничего не заметит, т.к. у него уже будет совпадать обновленный аватар и наш сохраненный файл, но нам уже не нужно хранить картинку на этом этапе + не понятно, как поведет себя попап, если от сервера пришла ошибка в ответ на сабмит, скорее всего также подменит аватарку, но в этом случае уже будет заметно несоответствие фотографии в профиле и в попапе.
2. Все еще отправляем все данные на сервер, даже если ничего не меняли. Лучше просто закрывать попап в этом случае.

2023-08-07 06:46 UTC, vierim commented
@VladislavSerKir комментарии Анастасии очень здравые. Нужно их реализовать.

2023-08-07 21:01 UTC, anastasia-bazaeva approved these changes
Отличная работа! Это довольно сложная часть проекта, и она функционирует корректно, отображается согласно макету, мобильное отображение попапа правильное на всех доступных для теста разрешениях мобильных устройств

2023-08-07 21:04 UTC, anastasia-bazaeva commented
Если есть желание, можно бонусом починить сторибук после мержа с девелоп) я сначала не погружалась, потом увидела, что в src\shared\ui\registration-notice\index.tsx после return null; нечитаемый символ

2023-08-09 05:47 UTC, vierim approved these changes
Отличная работа!

2023-08-09 05:47 UTC, merged