json server configured
vierim/YaPomogayu-frontend pull request #71
Opened 2023-08-01 13:31 UTC by anastasia-bazaeva

Подключила json-server к проекту, проверила, что данные пользователей подгружаются корректно, проверила все роуты, описанные в server/db.json
Также добавила новый скрипт, который сразу собирает проект, запускает сервер и сторибук:
npm run dev

2023-08-02 19:40 UTC, VladislavSerKir approved these changes
В целом все хорошо сделано, но я на будущее добавил бы информацию по созданию  пользовательских роутов из официального источника.

2023-08-02 19:40 UTC, VladislavSerKir commented on package.json
> +    "dev": "concurrently \"npm run server\" \"npm start\" \"npm run storybook\"",
Отлично что появился такой скрипт

2023-08-02 19:40 UTC, VladislavSerKir commented on server/README.md
> +- Если необходимо изменить объект, возвращаемый с сервера, при обращении к какому-либо эндпоинту, в файле db.json вы сможете отыскать ключ, совпадающим с именем нужного вам эндпоинта. Его значение -
Хорошо что добавила свою документацию с кратким но емким содержанием

2023-08-02 19:40 UTC, VladislavSerKir commented on server/routes.json
> +  }
По документации в github [json-server](https://github.com/typicode/json-server) описывается немного другой процесс создания пользовательских роутов. 
![2023-08-02_22-18-27](https://github.com/vierim/YaPomogayu-frontend/assets/83783362/02335a4c-484e-43ab-a5c0-5f245695fe29)
Хотелось бы и эту информацию для справки добавить в нашу документацию
Причем нигде не нашел информации что роуты можно описывать в стиле camelCase. Я так полагаю это как ссылка на ключи в объекте в db.json. В целом мне только этот момент показался непрозрачным а так запрос отправляется на наш запущенный сервер, установленный локально

2023-08-02 19:40 UTC, VladislavSerKir commented on src/config/api-config.ts
> +export const API_URL = 'http://localhost:3001';
![2023-08-02_22-34-40](https://github.com/vierim/YaPomogayu-frontend/assets/83783362/98a92dcf-f560-472b-bffb-df11114e62f9)
![2023-08-02_22-35-51](https://github.com/vierim/YaPomogayu-frontend/assets/83783362/74cbdfd4-5885-46e4-b319-8f8073c16b32)

2023-08-03 06:09 UTC, vierim requested changes
Отличная работа! 
Нужно внести небольшие правки в инструкцию и разобраться, как же правильно писать роуты.

2023-08-03 06:09 UTC, vierim commented on server/routes.json
> +  }
В целом достаточно линку на документацию, как мне кажется (https://www.npmjs.com/package/json-server) и разобраться все таки, как корректно делать роуты - как в доке или через camelCase. 
Прям сильно погружаться не вижу смысла - нам нужны базовые возможности, пока у нас нет бека, а рендерить что-то надо)

2023-08-03 11:05 UTC, anastasia-bazaeva commented on server/routes.json
> +  }
@VladislavSerKir @vierim да, по поводу официальной документации, я конечно же сперва пробовала сделать как в официальном примере. Но так просто не работает для наших целей, db.json ругается, если в ключе используется символ "/". 
Если использовать роуты типа user/:id , то прописывать отдельно через camelCase такой ключ в db.json не нужно, json-server сам найдет в объектах, хранящихся по ключу user тот, у которого нужный id и создаст к нему роут. Но вот если нужен роут вида user/activate/:id , то ключ user/activate/ в файле db.json создать не получится, его нужно будет заменить на другое значение, и указать его в кастомных роутах согласно доке readme. 
Если посмотрите еще раз на пример из официальной доки, то там указаны адреса из db.json только для простого роута posts без вложенности. Айдишка не в счет, она ищется, и под нее создается роут вида posts/1, как я уже описала выше, автоматически тупо поиском объекта с нужным id в массиве по ключу posts.

2023-08-03 11:12 UTC, anastasia-bazaeva commented on server/routes.json
> +  }
Из официальной документации наверное стоит отдельно забрать только то, что по роутам можно осуществлять фильтрацию и поиск по полям объектов, хранящихся на описанном роуте. Способов причем чуть больше, чем, в примере с поиском по совпадению в категории. Могу описать, если нужно будет использовать

2023-08-03 12:24 UTC, anastasia-bazaeva commented
Сделала коммит с изменениями в readme:
- поправила команды на npm i/npm ci
- добавила ссылку на официальную документацию
- добавила примеров с возможностями фильтровать, сортировать и т.д. в запросах

2023-08-03 12:53 UTC, merged