feat UI/user card
vierim/YaPomogayu-frontend pull request #72
Opened 2023-08-02 15:10 UTC by olgushe4ka

Есть ощущение, что я неверно поняла, как инкапуслировать логику кликов на кнопки внутри карточки и как работать с Апи

2023-08-03 06:36 UTC, vierim commented
@olgushe4ka на счет работы с Api - сложная тема пока. Давай начнем с простого - визуальная часть. Где мы можем увидеть карточки, которые сделала? Может есть смысл накидать разные карточки на http://localhost:3000/profile/admin/requests ?

2023-08-03 13:12 UTC, BreadLinx commented
Привет.

1. Разбей пожалуйста код на логические куски. Сложно читать, все вплотную друг к другу.

2. Пожалуйста доделай storybook, не видно все возможные вариации карточек. Я полагаю что сторибук остался нетронут.

3. У меня вопрос к @vierim , разве этот компонент ui? Не widget? В компоненте есть логика своя, можно выделить фичи и сделать как виджет под все вариации.

4. Нужно поменять name у инпута про фамилию у реципиента на name. Сейчас там email.

5. Я думаю карточкам нужен адаптив. Нужно сделать

2023-08-03 13:25 UTC, vierim commented
3. Да, логично было бы перенести в слой widgets.

2023-08-03 18:11 UTC, olgushe4ka commented
@BreadLinx 
Привет, поправила по твоим замечаниям,

кроме 5 пункта, про адаптив,  ширина карточки 276px, она уже адаптирована

2023-08-04 08:13 UTC, vierim commented
@olgushe4ka посмотри, пожалуйста, мобильную версию макета. Там есть два варианта карточки - https://disk.yandex.ru/i/OKXMt1BqIiqljg

2023-08-04 16:49 UTC, olgushe4ka commented
@vierim Я когда делала адаптив, поняла, что не касалась вообще User Card админов, сделала только для волонтеров и риципиентов. 
Для админов тоже надо сделать?

2023-08-04 18:15 UTC, BreadLinx commented
Да

2023-08-04 18:46 UTC, vierim commented
@olgushe4ka Да, сделай, пожалуйста, верстку и сворачивание / разворачивание. Логику клика на галочки пока можно не делать.

2023-08-04 19:00 UTC, vierim requested changes

2023-08-04 19:00 UTC, vierim commented on src/widgets/user-card/index.tsx
> +  avatarLink = 'https://i.pravatar.cc/300',
Давай мы все таки не будем передавать в качестве аватара какое-то значение по умолчанию. Если аватара нет, должна выводиться заглушка. Если логика заглушки нет, надо ее сделать.
А то не хорошо будет, если вдруг такое значение по умолчанию улетит в продакшен.

2023-08-08 17:22 UTC, BreadLinx commented
1. Компонент на 280 строк, явно нужно декомпозировать его. Сделать фичи, энтитис.

2. Из того что в глаза бросилось. Нужно поправить инпуты. Они на разных вариациях разные.

![image](https://github.com/vierim/YaPomogayu-frontend/assets/90373473/fdf36db4-a2b2-4ede-b974-864347ee6d45)

2023-08-09 14:14 UTC, olgushe4ka commented
Декомпозировала элементы по ролям, но не уверена, что так правильно,
Инпуты поправила

2023-08-10 18:02 UTC, BreadLinx approved these changes
Все хорошо

2023-08-10 18:54 UTC, vierim requested changes
С одной стороны работа хорошая. С другой стороны, есть серьезные замечания к изменениям вокруг, которые надо исправить, прежде чем мы сможем это залить в рабочую ветку.

2023-08-10 18:54 UTC, vierim commented on src/entities/user/ui/user-info/volunteer-info/volunteer-info.tsx
> +  children?: any;
С какой целью мы описываем children в пропсах этого компонента и не используем их в самом компоненте?

2023-08-10 18:54 UTC, vierim commented on src/pages/master-admin/index.tsx
Данной страницы больше не существует.

2023-08-10 18:54 UTC, vierim commented on src/pages/admin/index.tsx
Данной страницы больше не существует. Для отображения компонента есть 4 страницы, где ты можешь вывести примеры:
RequestsVolunteersPage
RequestsRecipientsPage
RequestsNotprocessedPage
RequestsAdminsPage

Только очень тебя прошу - добавь примеры пользователей в моковый апи и подгружай их оттуда (можно прямо в useEffect компонента).

2023-08-10 18:54 UTC, vierim commented on src/shared/ui/registration-notice/styles.module.css
А зачем ты хочешь удалить тут все стили?

2023-08-13 05:38 UTC, vierim requested changes
Отличная работа! Осталось немного допилить компонент AdminActions и в продакшен (ну то есть в develop). Комментарии в файле самого компонента.

2023-08-13 05:38 UTC, vierim commented on src/widgets/user-card/components/admin-actions.tsx
> +import React, { useState } from 'react';
Импортировать React в данном случае не нужено. Он сам по себе нигде в коде не используется.

2023-08-13 05:38 UTC, vierim commented on src/widgets/user-card/components/admin-actions.tsx
> +      />
Судя по макету логин администратора нельзя редактировать. Может тогда есть смысл убрать тут input?

2023-08-13 05:38 UTC, vierim commented on src/widgets/user-card/components/admin-actions.tsx
Два комментария по данному компоненту я написал в коде и еще одно замечание будет здесь - компонент не соответсвует макету, а именно:
- админу нельзя позвонить или написать - https://disk.yandex.ru/i/JJkhgmaZHavSng
- блок с галочками не соответствует макету - https://disk.yandex.ru/i/H04bsPR2i58Ayg (шрифты, отступы)

2023-08-14 11:35 UTC, olgushe4ka commented on src/widgets/user-card/components/admin-actions.tsx
Поправила

2023-08-14 12:26 UTC, vierim requested changes

2023-08-14 12:26 UTC, vierim commented on src/widgets/user-card/styles.module.css
> +  font-family: Nunito Sans;
Сам шрифт давай оставим Golos

2023-08-14 16:09 UTC, merged