feat: registration notice
vierim/YaPomogayu-frontend pull request #74
Opened 2023-08-04 07:05 UTC by olgushe4ka

[Сделать новый компонент для уведомления пользователей #73](https://github.com/vierim/YaPomogayu-frontend/issues/73)

2023-08-04 08:07 UTC, vierim requested changes
Нужно поправить некоторые моменты.

2023-08-04 08:07 UTC, vierim commented on src/shared/ui/registration-notice/index.tsx
> +  settingText = 'Спасибо за регистрацию. Как только администратор подтвердит Вашу учетную запись, Вы сможете откликаться на заявки.',
Мне кажется, что нет смысла в дефолтном значении (тем более с текстом для одной какой-то роли), с учетом того, что этот пропс обязательный. 
Давай лучше добавим в компонент проверку, что возвращать null (или undefined, не помню, что там корректно), если длина переданной строки равна нулю.

2023-08-05 12:11 UTC, KirillKamratov requested changes
Отличная работа! 
Оставил несколько комментариев в коде, на которые стоит обратить внимание.

Также, необходимо поправить стили - насколько я понимаю, не должны сдвигаться имеющиеся на странице компоненты, а сейчас (обращу внимание на то, что я просто вставил окошко в рандомное место на странице регистрации).

<img width="1440" alt="Снимок экрана 2023-08-05 в 15 08 29" src="https://github.com/vierim/YaPomogayu-frontend/assets/102192184/89dc4a05-4d74-4806-9d65-eb27e965d110">

Я сталкивался с подобной задачей, когда писал компонент DropDown. Это можно исправить или через стили, или через React Portal.

2023-08-05 12:11 UTC, KirillKamratov commented on src/shared/ui/registration-notice/styles.module.css
> +  box-shadow: 0px 4px 32px 0px #00000029, 0px 0px 4px 0px #0000000a;
В случае, если ты задаешь значение в 0 пикселей, px писать ненужно, можно просто оставить 0

2023-08-05 12:11 UTC, KirillKamratov commented on src/shared/ui/registration-notice/index.tsx
> +        onClick={() => console.log('message button pressed')}
Зачем что-то выводить в консоль в проде? Мне кажется, это лишнее

2023-08-05 14:26 UTC, vierim commented on src/shared/ui/registration-notice/index.tsx
> +        onClick={() => console.log('message button pressed')}
@KirillKamratov консоль это временное решение. Оно применяется в рамках всего проекта. Предлагаю пока оставить как есть, до разработки какой-то общей логики действий во всплывающих кнопках.

2023-08-05 14:28 UTC, KirillKamratov commented on src/shared/ui/registration-notice/index.tsx
> +        onClick={() => console.log('message button pressed')}
@vierim А, понял, тогда хорошо)

2023-08-05 14:30 UTC, olgushe4ka commented
> Отличная работа! Оставил несколько комментариев в коде, на которые стоит обратить внимание.
> 
> Также, необходимо поправить стили - насколько я понимаю, не должны сдвигаться имеющиеся на странице компоненты, а сейчас (обращу внимание на то, что я просто вставил окошко в рандомное место на странице регистрации).
> 
> <img alt="Снимок экрана 2023-08-05 в 15 08 29" width="1440" src="https://user-images.githubusercontent.com/102192184/258583634-89dc4a05-4d74-4806-9d65-eb27e965d110.png">
> Я сталкивался с подобной задачей, когда писал компонент DropDown. Это можно исправить или через стили, или через React Portal.

@KirillKamratov , я наоборот поняла, что оно появляется только после регистрации и будет висеть в конкретном месте, сдвигая остальное вниз.

@vierim, подскажи пожалуйста, как правильно?

2023-08-05 14:31 UTC, vierim commented
@KirillKamratov обрати, пожалуйста, внимание на макет, в данном случае компонент как раз сдвигает контент вниз.

2023-08-05 14:33 UTC, KirillKamratov commented
@vierim @olgushe4ka Действительно, прошу прощения, мне сначала показалось, что это должно работать как всплывающее окно
В таком случае, снимаю это замечание)

2023-08-05 14:33 UTC, vierim commented on src/shared/ui/registration-notice/index.tsx
> +    return null; // Or return undefined, depending on your use case
От этого комментария можно совсем отказаться. Возвращаем null и все)

2023-08-05 14:39 UTC, vierim commented
@KirillKamratov как итог - что нужно поправить в данном PR?

2023-08-05 14:41 UTC, KirillKamratov commented
@vierim @olgushe4ka Просто px убрать, там где 0 в css и убрать комментарий, получается)

2023-08-05 14:45 UTC, vierim approved these changes
Отличная работа. Далее:
- нужно поправить два небольших замечания @KirillKamratov;
- удалить закомментированные стили;
- залить к себе в ветку актальный develop и решить конфликты, если таковые будут.

И заливаем в develop.

2023-08-05 14:45 UTC, vierim commented on src/shared/ui/registration-notice/styles.module.css
> +} */
Закомментированный кусок стилей, если они больше не нужны, лучше тоже удалить.

2023-08-05 15:26 UTC, KirillKamratov approved these changes

2023-08-05 15:33 UTC, merged