refact/application-routing
vierim/YaPomogayu-frontend pull request #77
Opened 2023-08-05 12:49 UTC by BreadLinx

1. Переделал систему роутинга с учетом ролевой модели.

2. Переделал компонент бокового меню

3. Переделал компонент подменю на страницах реквестов у админов

2023-08-07 11:02 UTC, anastasia-bazaeva requested changes
Отличная работа! Выглядит круто, переходы работают. Есть небольшое замечание по логике переходов в профиле админа ниже.

2023-08-08 10:11 UTC, anastasia-bazaeva commented on src/pages/pick-role-page-temporary/index.tsx
> +// ЭТО ВРЕМЕННАЯ СТРАНИЦА ДЛЯ РУЧНОГО ВЫБОРА РОЛЕЙ. ДОСТУПНА ПО РОУТУ /pick
@BreadLinx Я перезапустила твою ветку, снимаю замечание про моковые объекты. Либо у меня локально отвалился сервер заодно со сторибуком (там сейчас закрытие с ошибкой из свежего девелоп), либо когда я работала с разными ветками дропнула скрипт и перезапустила уже без сервера. У тебя тут все в порядке

2023-08-08 17:08 UTC, anastasia-bazaeva commented on src/pages/pick-role-page-temporary/index.tsx
> +        return '/requests';
Вот тут только поменять тоже надо на profile/requests

2023-08-08 18:23 UTC, vierim approved these changes
Отличная работа!

2023-08-08 18:24 UTC, merged