Fix/UI map mark
vierim/YaPomogayu-frontend pull request #78
Opened 2023-08-05 21:30 UTC by Gyxer513

Задание выполнено.

Пришлось захардкодить данные для неавторизованного пользователя. Для замены хардкода данные для неавторизованного пользователя лучше получать с сервера. Вот приблизительный формат: 

 tasks: [
      {
        id: 24,
        title: 'Задача 24',
        category: {
          id: 5,
          name: 'Название категории 5',
          scope: 50,
        },
        recipient: {
          id: 6,
          createdAt: '2023-07-10T19:30Z',
          fullname: 'Нужна помощь',
          role: 'recipient',
          avatar: 'https://i.ytimg.com/vi/IeelNKvu65A/hqdefault.jpg',
          phone: '+7 (000) ***-**-**',
          address: 'переулок Каховского, 3',
          coordinates: [59.95252, 30.243239],
          status: 'confirmed',
        },
        volunteer: null,
        address: 'переулок Каховского, 3',
        coordinates: [59.95252, 30.243239],
        chatId: null,
      },
...{ }
    ],

2023-08-07 18:38 UTC, VladislavSerKir requested changes
Привет в целом проделана хорошая работа. Верстка компонента выполнена по макету. Но есть некоторые замечания.
1) Перед отправкой не сделал pull из оригинальной ветки develop.
2) В макете есть информативная иконка, отображающая количество очков за срочную задачу. Не увидел ее реализацию, возможно нужно уточнить у @vierim нужно ли ее делать в рамках данной задачи 
![2023-08-07_21-09-00](https://github.com/vierim/YaPomogayu-frontend/assets/83783362/e6b2f656-8523-406a-87d6-fd2e04631993)
3) Не смог проверить отображение обычной задачи (синего цвета) из-за отсутствия json-servera и возможности сделать свою таску (Все таски на данный момент берутся из swaggerhub). 
![2023-08-07_21-27-05](https://github.com/vierim/YaPomogayu-frontend/assets/83783362/bb96cfbe-0a19-4350-96df-3450b7369e9f)

2023-08-07 18:38 UTC, VladislavSerKir commented on src/shared/ui/map/Mark.tsx
> +          <img src="{{properties.avatar}}" alt={{properties.fullName}} class="task_avatar"/>
Аватар в окне не корректно отображается

2023-08-07 18:38 UTC, VladislavSerKir commented on src/shared/ui/map/Mark.tsx
> +          <button type="button" class="task_button"></button>
Кнопка отображения описания задачи отображается всегда. По макету она должна быть скрыта если описание больше определенного количества символов, в нашем случае больше 4 строк  
![2023-08-07_21-04-51](https://github.com/vierim/YaPomogayu-frontend/assets/83783362/569bdfc6-84a2-4a31-888c-5ffb45069bf4)

2023-08-07 18:38 UTC, VladislavSerKir commented on src/shared/ui/map/styles.css
> +.task_box {
Верстка соответствует макету, отлично

2023-08-10 08:24 UTC, Gyxer513 commented on src/shared/ui/map/Mark.tsx
> +          <img src="{{properties.avatar}}" alt={{properties.fullName}} class="task_avatar"/>
У меня аватар отображается, бывает что они не прогружаются со стороннего ресурса. 

![image](https://github.com/vierim/YaPomogayu-frontend/assets/102280477/6db90ed5-b853-45d8-8b15-176ea947bee3)

2023-08-10 08:25 UTC, Gyxer513 commented on src/shared/ui/map/Mark.tsx
> +          <button type="button" class="task_button"></button>
Исправлено.

2023-08-10 17:00 UTC, VladislavSerKir approved these changes
В целом компонент выглядит как на макете, хорошая работа!

2023-08-10 18:00 UTC, merged