feat balance-settings layout
vierim/YaPomogayu-frontend pull request #79
Opened 2023-08-06 10:44 UTC by olgushe4ka

https://github.com/vierim/YaPomogayu-frontend/issues/76

2023-08-07 21:05 UTC, KirillKamratov requested changes
Несоответствие макету (если я правильно воспользовался pixel perfect):

<img width="1019" alt="Снимок экрана 2023-08-08 в 00 03 31" src="https://github.com/vierim/YaPomogayu-frontend/assets/102192184/89bf85dd-30f7-4bc7-ac95-947773ba2402">

Также, отсутствует кнопка "сохранить"

Также, при попытке поменять количество баллов, страница падает, как при рендере, так и в сторибуке:

<img width="1440" alt="Снимок экрана 2023-08-08 в 00 05 03" src="https://github.com/vierim/YaPomogayu-frontend/assets/102192184/cf753af6-4ffc-4fae-86f9-0d707c31c77b">

<img width="1440" alt="Снимок экрана 2023-08-08 в 00 05 19" src="https://github.com/vierim/YaPomogayu-frontend/assets/102192184/c9c9a424-9752-4806-afd5-3134c2aeb56b">

2023-08-08 07:46 UTC, vierim commented
@olgushe4ka нужно исправить замечания, указанные Кириллом. От себя пока добавлю только пару моментов:
1. У компонента Input не нужен закрывающий тег </Input>, так как у него нет children'ов
2. В компоненте BalanceSettings 10 раз повторяется по сути одни и тот же код - название категории и данные о балах. Есть смысл вынести данную сущность в отдельный компонент, так как при малейшем изменении логики программист будет страдать.

2023-08-09 17:43 UTC, KirillKamratov requested changes
Есть некоторые исправления, но все еще имеет место быть несоответствие макету

<img width="1440" alt="Снимок экрана 2023-08-09 в 20 34 01" src="https://github.com/vierim/YaPomogayu-frontend/assets/102192184/5736b82b-e5e0-4ddc-8aed-3027620d99cc">

Достаточно будет того, что у тебя первое дело в списке ложилось идеально по pixel perfect, тогда остальные тоже лягут лучше.

Также, кнопка сохранить не должна быть объемной, как у тебя, на макете она плоская 

<img width="1440" alt="Снимок экрана 2023-08-09 в 20 41 11" src="https://github.com/vierim/YaPomogayu-frontend/assets/102192184/f435ffd4-8072-48a3-b8f9-0ce5108b34e4">

На скриншоте не очень хорошо видно, но если ты в лоб сравнишь то, что на макете (и в сторибуке) со своей кнопкой - увидишь отличия

+ те комментарии, которые есть в коде

2023-08-09 17:43 UTC, KirillKamratov commented on src/widgets/balance-settings/balance-settings.stories.tsx
> +  // argTypes: {
Если эта часть не нужна - ее лучше удалить, тк она нигде не используется

2023-08-09 17:43 UTC, KirillKamratov commented on src/widgets/balance-settings/styles.module.css
> +/*
Если эти стили не нужны - их лучше удалить

2023-08-09 18:48 UTC, vierim commented on src/widgets/balance-settings/index.tsx
> +        <BalanceSettingsItem
Список категорий можно получать сразу с json-сервера - они висят на ручке http://localhost:3001/category. В данном случае можно получать их прям в компоненте и не закидывать в редакс (так как для контента страниц будет скорее всего другая либо использоваться).

2023-08-09 18:51 UTC, KirillKamratov commented on src/widgets/balance-settings/index.tsx
> +        <BalanceSettingsItem
А, ну тогда, конечно, так намного проще

2023-08-10 06:00 UTC, olgushe4ka commented
Чтобы посмотреть страничку:
http://localhost:3000/pick
Выбрать роль администратора, потом "Создание заявки/редактирование заявки" и там вверху есть ссылка "Настроить баллы" и будет оно

2023-08-10 15:36 UTC, KirillKamratov requested changes
Проведен отличный рефакторинг, теперь код выглядит намного аккуратнее, но:

Я не смог, следуя твоей инструкции зайти на нужную страницу (возможно, делал что-то не так).

Все еще есть несоответствие макету:

<img width="1440" alt="Снимок экрана 2023-08-10 в 18 34 56" src="https://github.com/vierim/YaPomogayu-frontend/assets/102192184/e1d9f882-bd8a-4703-965a-1eece6b0110e"> 

+тот комментарий, касательно изменения баллов - страница не должна падать с ошибкой.

2023-08-10 15:36 UTC, KirillKamratov commented on src/widgets/balance-settings/index.tsx
> +      throw new Error('Function not implemented.');
Все таки ошибка выбрасываться не должна, мы должны иметь возможность менять количество баллов

2023-08-12 05:40 UTC, olgushe4ka commented
Убрала выбрасывание ошибки, но совсем до пиксель перфект не довела. 

На мой взгляд, сейчас все выглядит адекватно в рамках логики странички

2023-08-14 13:35 UTC, KirillKamratov approved these changes
Отличная работа!

Единственное "Но":

![image](https://github.com/vierim/YaPomogayu-frontend/assets/102192184/170ab06b-879d-46d7-b861-0196ab55913c)

Я думаю, стоит убрать переключатель на стрелочки, тк его нет на макете. Я думаю, это можно сделать с помощью стилей.

Касательно PP и стрелок - пусть тут @vierim ответит уже, как лучше)

2023-08-14 13:46 UTC, vierim requested changes
Нужно внести небольшие правки:
- по макету инпуты для цифр имеют определенный стиль - https://disk.yandex.ru/i/aRgsGfQk5S4OEg
- количество баллов у любой из категорий не может быть меньше 1 - https://disk.yandex.ru/i/SL-AgSv2hETRtg
- в мобильной версии https://disk.yandex.ru/i/uiyoi4PpNCDHsg нужно отцентровать компонент и сделать видимой кнопку сохранить, сейчас ее не видно за тенью футера
- также в мобильной версии (от 320px) не должна появляться горизонтальная прокрутка
- корректней сделать из этих инпутов и кнопки форму и вешать обработчик не на клик кнопки, а на сабмит формы.

2023-08-14 13:48 UTC, vierim commented
> Касательно PP и стрелок - пусть тут @vierim ответит уже, как лучше)

Я против неутвержденных стрелок в инпутах. На счет PP предлагаю оставить как есть.

2023-08-16 11:35 UTC, vierim requested changes
Хорошая работа. Но нужно еще несколько деталей поправить.

2023-08-16 11:35 UTC, vierim commented on src/widgets/balance-settings/components/balance-settings-item.tsx
> +    <form onSubmit={handleSubmit}>
В рамках данного кода у тебя получается каждый BalanceSettingsItem - отдельная форма. Это не правильно. Все BalanceSettingsItem и кнопка должны лежать в одной форме.

2023-08-16 11:35 UTC, vierim commented on src/widgets/balance-settings/index.tsx
> +    <div className={classnames(styles.container, extClassName)}>
Вот все, что лежит внутри этого div - должно быть обернуто в форму, на которой висит слушатель события onSubmit

2023-08-16 11:35 UTC, vierim commented on src/widgets/balance-settings/components/balance-settings-item.tsx
> +  const handleSubmit = (e: { preventDefault: () => void }) => {
Соответственно этот слушатель должен быть в родительском компоненте, а не здесь.

2023-08-17 14:56 UTC, vierim approved these changes
Отличная работа!

2023-08-17 14:56 UTC, merged