Feat/permissions
vierim/YaPomogayu-frontend pull request #84
Opened 2023-08-09 18:03 UTC by anastasia-bazaeva

В этой ветке сделала сразу две свои задачи, т.к. вторая совсем маленькая и нужна была мне для хуков: 

1. Поправила модель юзера и вынесла отдельно поле isActive, которое будет отображать активен или заблокирован юзер.

2. Сделала два хука - usePermissions и useUser. 

- Первый хук принимает в качестве аргументов массив условий и роль для которых мы хотим настроить доступность компонента/страницы/элемента и возвращает true, если пользователь удовлетворяет хотя бы одному из них. Например, фильтр для Категории 1 доступен пользователям со статусами Подтвержден, Активен и Верифицирован, а для Категории 4 только со статусами Активен и Верифицирован. Если юзер имеет один из этих статусов, то хук вернет для него true. 
- Также сделала хук useUser, который возвращает true/false на основании поля isActive. Заменила предыдущее понимание авторизации по роли, т.к. у заблокированного пользователя роль тоже есть, и его может в какой-то момент пустить куда не нужно, если из-за чего-то не сбросился токен и юзера еще не разлогинило. 

5. Сделала пример использования на странице реципиента и волонтера. Можно поиграться и поменять в db.json статус волонтера и реципиента и посмотреть, как блокируется или становится неактивным нажатие на фильтры, кнопку "Откликнуться" или "Создать новую заявку".

2023-08-10 17:44 UTC, BreadLinx approved these changes
Все хорошо

2023-08-10 19:29 UTC, vierim requested changes
Отличная работа! Нужно внести небольшие правки, замержить актуальный develop и заливаем в рабочую ветку.

2023-08-10 19:29 UTC, vierim commented on src/shared/ui/map/Mark.tsx
> +    const isGranted = usePermission([CONFIRMED, ACTIVATED, VERIFIED]);
В данном случае некорректный вызов хука. В хук обязательным параметром нужно передавать роль. Если бы в начале файла не был отключен typescript (из-за плагина с картами), то IDE подсветила бы ошибку.

2023-08-10 19:29 UTC, vierim commented on src/shared/hooks/use-permission.tsx
> +export default function usePermission(requirments: Array<any>, role: string) {
`Array<any>` не очень удачное объявление. Лучше все таки конкретизировать варианты.

2023-08-10 19:29 UTC, vierim commented on src/shared/hooks/use-permission.tsx
> +  const user = useAppSelector((state) => state.user.data);
Лучше взять из стора только нужные параметры, а не всю data. Так меньше шансов на перерендеры.

2023-08-10 19:41 UTC, vierim commented
Сделал ревью. Нужно внести небольшие изменения. 

Отдельно хочу обсудить следующий момент:

> т.к. у заблокированного пользователя роль тоже есть, и его может в какой-то момент пустить куда не нужно, если из-за чего-то не сбросился токен и юзера еще не разлогинило.

Сам по себе хук имеет право на жизнь. Но я пока не могу понять опасений относительно заблокированного юзера и необходимости свойства isActive. 
Есть два варианта, при которых пользователь может быть заблокирован:
1) Пользователь не в сети. Его заблокировали. Он пытается войти. И получает от API ошибку с каким-то кодом и текстом. Все. Он не получает в ответ вместе с ошибкой объект со своими данными и нам просто нечего сохранять в стор. И при получении ошибки от API мы делаем редирект на страничку для заблокированного пользователя. Даже если он руками введет адрес какой-то страницы и каким-то чудом на нее попадет, он все равно ничего не увидит, так как при запросе на сервер не будет актуального JWT ключа.
2) Пользователь в сети. И в этот момент его блокируют. Он может видеть тот контент, который у него закеширован. Но кеш сразу сотрется при  refetch данных (то есть каждые 30 секунд), так как его JWT ключ будет заблокирован уже и он получит ошибку. При любой попытке что-то сделать (получить данные, отправить данные) он сразу же получит отлуп от сервера.

В целом я хочу сказать, что не может быть такого, что пользователь заблокирован, мы об этом знаем, но его JWT ключ все еще действителен. Источником истины в данном случае является сервер. Если JWT ключ работает, мы все рендерим, если не работает, рендерим ошибку.

2023-08-11 11:42 UTC, vierim approved these changes
Отличная работа!

2023-08-11 11:46 UTC, merged