refactored filter feature
vierim/YaPomogayu-frontend pull request #96
Opened 2023-08-15 14:31 UTC by BreadLinx

Переработал фильтр

2023-08-15 16:46 UTC, anastasia-bazaeva requested changes
Хорошая работа! Все фильтры работают, отображают нужные компоненты и кнопки.
У меня есть несколько замечаний:
- Кажется, что все используемые компоненты - это один и тот же фильтр, просто который находится в состоянии разного отображения. У нас сейчас довольно много дублирующих функционал друг друга компонентов фильтра, когда можно сделать только один общий фильтр, который принимал бы помимо текущих пропсов роль, кому его показывать, и тип - для карты, для активных/закрытых заявок и т.д.
- В сторибуке можно сделать сразу отображение раскрытого попапа с фильтром вместе с панелью, на которой находится кнопка. Отдельно кнопку с икнокой можно будет перенести в файл рядышком и показать просто вид всех панелей с кнопкой фильтра, которые у нас есть.

2023-08-15 16:46 UTC, anastasia-bazaeva commented on src/features/filter/components/filters/active-tasks-filter/active-tasks-filter.tsx
> +            <RadiusBlock
Мы используем практически одинаковые конструкции фильтра для разных ролей. Можно сделать условный рендеринг тех элементов, которые зависят от роли через выражения вида {role === 'recipient' &&()} так у нас будет чуть меньше дублирующегося кода

2023-08-15 17:35 UTC, BreadLinx commented
> * Кажется, что все используемые компоненты - это один и тот же фильтр, просто который находится в состоянии разного отображения. У нас сейчас довольно много дублирующих функционал друг друга компонентов фильтра, когда можно сделать только один общий фильтр, который принимал бы помимо текущих пропсов роль, кому его показывать, и тип - для карты, для активных/закрытых заявок и т.д.

Я не понимаю зачем делать один огромный компонент фильтра. Все что у нас сейчас есть в каждом фильтре я максимально сжал, там по пусти осталось только составное фильтра. Обертку с логикой кнопки и саму обертки открытия фильтра я вынес и инкапсулировал. Если сделать 1 огромный фильтр он наоборот в позже создаст проблемы чем делать под каждую задачу отдельный. Там нет фильтра в разном отображении там как раз собранные под каждую задачу отдельные фильтры.

Мне нужен комментарий Владимира по этому вопросу, если примите решение что все таки нужно выделить, я выделю, но свое обоснование я привел.

2023-08-15 17:37 UTC, BreadLinx commented on src/features/filter/components/filters/active-tasks-filter/active-tasks-filter.tsx
> +            <RadiusBlock
Я думаю что это сделает код менее читабильным. Сейчас отчетливо видно как будет выглядить фильтр.

Мне нужен комментарий Владимира по этому вопросу.

2023-08-15 17:37 UTC, BreadLinx commented
Сторибук добавлю

2023-08-16 05:35 UTC, vierim commented
@BreadLinx Платон, привет! 
Анастасия обозначила существующую проблему с дублированием кода. Пожалуйста, постарайся воспринимать это конструктивно.

Я понимаю, с какой целью дублирование кода было сделано, но тем не менее это не самая хорошая практика, так как:
- в случае изменения пропсов или логики отдельных блоков фильтра нам нужно будет не забыть все поправить;
- читабельность одного конкретного фильтра действительно улучшилась, но лишь отчасти - читая код фильтра ты все равно должен сначала понять, для какой роли ты читаешь код;
- подключить новый набор фильтров к странице все равно достаточно сложно - много пунктов в инструкции.

Саму по себе логику фильтра ты сделал отлично. Фильтр хорошо разделен на слои и у каждого из них своя зона ответственности. Прям глаз радуется. Теперь давай подумаем, как можно исправить ситуацию с созданием очень похожих файлов для разного набора секций фильтра. 

В идеале это должен быть один компонент, как написала Анастасия. Но давай не будем завязываться на роль пользователя и тип страницы, куда мы подгружаем фильтр. Такая логика увеличивает связность кода и при ее применение сложнее понять, где какой набор элементов фильтра должен рендерится. А нужно все это наоборот еще упростить. Я предлагаю поразмышлять на следующим вариантом:

Вот в этой части кода:
```
<SmartHeader
  text="Активные заявки"
  icon={
    <Icon color="blue" icon="ActiveApplicationIcon" size="54" />
  }
  filter={<ActiveTasksFilter />}
/>
```

Вместо компонента отдельно взятого фильтра `<ActiveTasksFilter /> `мы можем передавать какой-то общий компонент `<Filter />`, в который мы будем накидывать список нужных нам блоков фильтра через пропсы или объект настроек. Например так:
```
const filterItems: IFilterItems = {
  categories: true,
  radius: true,
  time: false,
  date: false,
  ...
}

...

  filter={
    <Filter items={filterItems} />
  }
/>
```

И далее уже в компоненте `<Filter>` мы этот объект настроек парсим и выдаем назад только те блоки, которые запрашивает страница. Тем самым мы уменьшаем дублирование кода и сразу на странице можем видить, какие блоки фильтра у нас подключены. Да и новые подключить проще. Например, если мы решим в фильтр активных заявок у рецепиента подключить еще возможность фильтрации по времени, нам просто нужно будет написать `true`в объекте настроек.

2023-08-19 19:33 UTC, BreadLinx commented
Привет.
Теперь я понял вашу точку зрения. Это действительно лучше чем моя первоначальная реализация.
Для этого и нужна команда.
😊😊😊

2023-08-22 04:25 UTC, vierim approved these changes
Отличная работа! Почини, пожалуйста, конфликты с текущим кодом в develop и можно заливать.

2023-08-22 18:07 UTC, merged